version: '3.8'

services:
  service-registry:
    image: service-registry
    ports:
      - "8761:8761"
    networks:
      - eureka-network

  course-service:
    image: course-service
    ports:
      - "8082:8082"
    depends_on:
      - service-registry
      - mysql
    networks:
      - eureka-network

  finance-service:
    image: finance-service
    ports:
      - "8083:8083"
    depends_on:
      - service-registry
      - mysql
    networks:
      - eureka-network

  instructor-service:
    image: instructor-service
    ports:
      - "8084:8084"
    depends_on:
      - service-registry
      - mysql
    networks:
      - eureka-network

  learner-service:
    image: learner-service
    ports:
      - "8085:8085"
    depends_on:
      - service-registry
      - mysql
    networks:
      - eureka-network

  notification-service:
    image: notification-service
    ports:
      - "8086:8086"
    depends_on:
      - service-registry
    networks:
      - eureka-network

  user-service:
    image: user-service
    ports:
      - "8087:8087"
    depends_on:
      - service-registry
      - mysql
    networks:
      - eureka-network

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Root@1234
      MYSQL_DATABASE: microservices
      MYSQL_USER: user
      MYSQL_PASSWORD: Root@1234
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - eureka-network

networks:
  eureka-network:
    driver: bridge

volumes:
  db-data:
