spring.application.name=api-geteway
server.port=8765
#server.port=4001

# Enable dynamic service discovery
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

#eureka.client.service-url.defaultZone=http://host.docker.internal:8761/eureka
eureka.client.service-url.defaultZone=http://service-registry:8761/eureka
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka
#eureka.client.service-url.defaultZone=http://localhost:4000/eureka

